// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZDLoanCalculator.Data.EntityFramework;

namespace ZDLoanCalculator.Data.EntityFramework.Migrations
{
    [DbContext(typeof(ZDLoanCalculatorContext))]
    [Migration("20190708214201_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("ZDLoanCalculator.Core.Models.LoanType", b =>
                {
                    b.Property<string>("Key");

                    b.Property<string>("Description");

                    b.Property<float>("InterestRate");

                    b.HasKey("Key");

                    b.ToTable("LoanTypes");

                    b.HasData(
                        new { Key = "house", Description = "House loan", InterestRate = 0.035f },
                        new { Key = "car", Description = "Car loan", InterestRate = 0.065f },
                        new { Key = "consumer", Description = "Consumer loan", InterestRate = 0.105f }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
